### ISSUE TITLE
Updates django to latest version during install

### ISSUE THREAD

**Issue by maratumba** [escaped/django-exiffield#10]
In the documentation the Django requirement is >1.8. I have Django 1.11.7 and pip wanted to upgrade Django to the latest version (3.0) during `django-exiffield` install which brakes everything and it is difficult to roll back.

**Comment by escaped** [comment]
Hi @maratumba 

that's interesting and I am not sure why you are getting this behaviour as the [requirements](https://github.com/escaped/django-exiffield/blob/864e09e7dce03229bdc9c981ed97c930f48e90b2/pyproject.toml#L34) for this package don't include `Django` at all.

**Comment by escaped** [comment]
Digging further, it looks like [`jsonfield`](https://github.com/rpkilby/jsonfield2/blob/0dbb4f907ed28af114e683ba79ed92b4b4fdc228/setup.py#L15) requires `django >= 2.2`. So as long as we are dependent on `jsonfield2` ([`jsonfield`](https://github.com/rpkilby/jsonfield/)), we have to use a newer Django version.

I'll will update the README accordingly. Sorry for the inconveniences.

**Comment by escaped** [comment]
Documentation has been updated in #13
