### ISSUE TITLE
Use jsonfield instead of jsonfield2

### ISSUE THREAD

**Issue by escaped** [escaped/django-exiffield#12]
`jsonfield2` is deprecated in favour of [`jsonfield`](https://github.com/rpkilby/jsonfield/).

**Comment by MohammedBajuaifer** [comment]
Hi @escaped, Is this issue still open? would like to work on it!

**Comment by escaped** [comment]
@MohammedBajuaifer yes, the issue is still and you are free to work on this if you want. If you tackle this issue, could you please have a look at #10 as well? It's basically about updating the documentation to reflect the minimal required Django version, which is enforced by the jsonfield dependency. Thank you :)
If you need any help, pleas let me know.

**Comment by MohammedBajuaifer** [comment]
Hi @escaped, thank you! I was looking through the code but I didn't see a place where jsonfield2 being used. Might need a bit of explanation if you don't mind

**Comment by escaped** [comment]
Sure, I haven't digged into the code yet again, but if I remember correctly the python package name (basically what you import in your code) is called `jsonfield` even though the package you are installing is called `jsonfield2`. So it seems like you "just" need to update the dependency in the `pyproject.toml` (generated by `poetry`) and make sure that all tests are passing :)

**Comment by escaped** [comment]
HI @MohammedBajuaifer,

just wanted to check in if you are still working on this issue as I would like to include these changes into the next release. I just want to know where things are :)

**Comment by escaped** [comment]
Sorry, @MohammedBajuaifer  for taking over, but I wanted to get a new release out of the door. Thank you for looking into it though :)
